use serde::{Deserialize, Serialize};
use tokio::time::sleep;
use forward_proxy::handler::types::request::InitTunnelRequest;
use forward_proxy::handler::types::response::InitTunnelResponseToINT;
use crate::mock::data::EncryptedMessage;

mod mock;

#[derive(Serialize, Deserialize)]
pub struct InitEncryptedTunnelRequest {
    pub public_key: Vec<u8>,
}

#[tokio::test]
async fn test_init_tunnel_data() {
    mock::init().await;

    sleep(std::time::Duration::from_secs(1)).await; // Wait for the mock server to start

    let client = reqwest::Client::new();
    let body = InitTunnelRequest {
        public_key: Vec::from(mock::data::MOCK_NTOR_CLIENT_PUBLIC_KEY.clone()),
    };

    let response = client
        .post(
            format!(
                "http://localhost:{}{}?backend_url={}",
                mock::data::FORWARD_PROXY_PORT,
                mock::data::INIT_TUNNEL_API_PATH,
                mock::data::BACKEND_URL
            )
        )
        .json(&body)
        .send()
        .await;

    println!("Response: {:?}", response);

    match response {
        Ok(res) => {
            let status = res.status();
            let res_body: InitTunnelResponseToINT = res.json().await.expect("Failed to parse response body");
            println!("Response body: {:?}", res_body);

            assert_ne!(res_body.int_fp_jwt.len(), 0, "INT_FP_JWT should not be empty");
            assert_ne!(res_body.int_rp_jwt.len(), 0, "INT_RP_JWT should not be empty");
            assert_eq!(res_body.int_rp_jwt, mock::data::MOCK_INT_RP_JWT, "INT_RP_JWT does not match expected value");
            assert_ne!(res_body.int_fp_jwt, res_body.int_rp_jwt, "INT_FP_JWT and INT_RP_JWT should not be the same");
            assert_ne!(res_body.int_fp_jwt, mock::data::MOCK_FP_RP_JWT, "INT_FP_JWT should not match FP_RP_JWT");
            assert_ne!(res_body.int_rp_jwt, mock::data::MOCK_FP_RP_JWT, "INT_RP_JWT should not match FP_RP_JWT");
            assert_eq!(res_body.ephemeral_public_key, Vec::from(mock::data::MOCK_NTOR_SERVER_EPHEMERAL_PUBLIC_KEY.clone()), "Public key does not match expected value");
            assert_eq!(res_body.t_b_hash, Vec::from(mock::data::MOCK_NTOR_SERVER_T_B_HASH.clone()), "nTor t_b_hash does not match expected value");
            assert_eq!(res_body.ntor_server_id, mock::data::BACKEND_URL.to_string(), "nTor server ID does not match expected value");
            assert_eq!(res_body.ntor_static_public_key, Vec::from(mock::data::MOCK_NTOR_SERVER_STATIC_PUBLIC_KEY.clone()), "nTor static public key does not match expected value");

            // validate the JWT tokens, it was generated by forward-proxy using the mock secret and should be valid
            utils::jwt::verify_jwt_token(&res_body.int_fp_jwt, &Vec::from(mock::data::MOCK_JWT_SECRET.to_string())).expect("Failed to verify INT_FP_JWT");

            assert_eq!(status, reqwest::StatusCode::OK, "Expected status 200 OK");
        }
        Err(err) => {
            assert!(false, "Request failed: {}", err);
        }
    }
}

#[tokio::test]
async fn test_proxy_data() {
    mock::init().await;

    sleep(std::time::Duration::from_secs(3)).await; // Wait for the mock server to start

    let client = reqwest::Client::new();
    let body = EncryptedMessage {
        nonce: mock::data::MOCK_PROXY_REQUEST_NONCE,
        data: mock::data::MOCK_PROXY_REQUEST_DATA.to_vec(),
    };

    let body_bytes = utils::type_to_bincode(&body);

    let response = client
        .post(
            format!(
                "http://localhost:{}{}",
                mock::data::FORWARD_PROXY_PORT,
                mock::data::PROXY_API_PATH,
            )
        )
        .header("int_fp_jwt", mock::data::MOCK_INT_FP_JWT)
        .header("int_rp_jwt", mock::data::MOCK_INT_RP_JWT)
        .body(body_bytes.clone())
        .send()
        .await;

    println!("Response: {:?}", response);

    match response {
        Ok(res) => {
            let status = res.status();
            let res_body_bytes: axum::body::Bytes = res.bytes().await.expect("Failed to parse response body");

            println!("Response body bytes: {:?}", res_body_bytes);

            let res_body: EncryptedMessage = utils::bincode_to_type(&res_body_bytes).expect("Failed to decode response body");
            println!("Response body: {:?}", res_body);

            assert_eq!(res_body.nonce, mock::data::MOCK_PROXY_RESPONSE_NONCE, "Response nonce does not match expected value");
            assert_eq!(res_body.data, mock::data::MOCK_PROXY_RESPONSE_DATA.to_vec(), "Response data does not match expected value");

            assert_eq!(status, reqwest::StatusCode::OK, "Expected status 200 OK");
        }
        Err(err) => {
            assert!(false, "Request failed: {}", err);
        }
    }
}