[package]
name = "pingora-router"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
pingora = { version = "0.5.0", features = ["lb", "boringssl"] }
serde = "1.0.219"
serde_json = "1.0.140"
