[package]
name = "proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait="0.1"
#pingora = { version = "0.3", features = [ "lb" ] }
pingora = { git = "https://github.com/dtpthao/pingora.git", tag = "0.4.1", features = [ "lb" ]  }
bytes = "1.10.1"
clap = { version = "3.2.25", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.8.26"
env_logger = "0.11.7"
log = "0.4.27"
chrono = "0.4.40"

#[patch.crates-io]
#sfv = { git = "https://github.com/undef1nd/sfv.git", tag = "v0.9.4" }