[upstream]
host="localhost"
port=0

[log]
level="DEBUG"
path="console"

[server]
host="localhost"    # The host where the reverse proxy will listen
port=6191           # The port where the reverse proxy will listen

[handler]
jwt_virtual_connection_secret="this is 32-byte wgp's jwt secret"
jwt_exp=24          # in hours
ntor_server_id="ReverseProxyServer"
ntor_static_secret="this is 32-byte nTorStaticSecret"
