'use strict';

const express = require('express');

const app = express();
const PORT = process.env.PORT || 5001;

// X.509 certificate containing the X25519 public key derived from
// NTOR_STATIC_SECRET = "this is 32-byte nTorStaticSecret"
// Generated by certs/ntor/generate_ntor_cert.py
const NTOR_RP_CERT = `-----BEGIN CERTIFICATE-----
MIH4MIGroAMCAQICFCAy9VJULMTDz4YxgT3Yj3gny6HTMAUGAytlcDAcMRowGAYD
VQQDDBFyZXZlcnNlX3Byb3h5LmNvbTAeFw0yNTA3MTYxMDMzMzdaFw0yNjA3MTYx
MDMzMzdaMB0xGzAZBgNVBAMMElJldmVyc2VQcm94eVNlcnZlcjAqMAUGAytlbgMh
AIPSJGUnvz2lHXBelXjKvaqXPvdH0P+QrTTf792Z4SgKMAUGAytlcANBANMvwCl1
B8oRatOTicKGmPlO6wUj3bmhd5ldOcd3xLB1h47HTRJs8mdTWD3pqayPGGnuYRsX
NjCXOCyH/VbUlQM=
-----END CERTIFICATE-----`;

app.get('/healthcheck', (req, res) => {
    res.json({ status: 'ok' });
});

// Returns the NTor X.509 certificate for the reverse proxy.
// FP calls this endpoint before performing the NTor handshake.
app.get('/api/v1/ext/client-cert', (req, res) => {
    const backendUrl = req.query.backend_url || '';
    res.json({
        cert: NTOR_RP_CERT,
        client_id: `smoke-test-client-${Date.now()}`,
        backend_url: backendUrl,
    });
});

app.listen(PORT, '0.0.0.0', () => {
    console.log(`Mock auth server running on port ${PORT}`);
});
