name: End-to-end tests for Frontend->FP->RP->Backend
on: [pull_request]
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upgrade node
        uses: actions/setup-node@v4
        with:
          node-version: "23.x"
      - name: Build Forward Proxy
        run: |
          cd forward-proxy && cargo update && cargo build
      - name: Build Reverse Proxy
        run: |
          cd reverse-proxy && cargo update && cargo build
      - name: Run services and do e2e tests
        run: |
          npm i -g concurrently && make run &
          for attempt in {1..20}; do sleep 2; if curl -s http://localhost:5173/ > /dev/null; then break; fi; done
          for attempt in {1..20}; do sleep 2; if curl -s http://localhost:3000/ > /dev/null; then break; fi; done
          for attempt in {1..20}; do sleep 2; if curl -s http://localhost:6191/ > /dev/null; then break; fi; done
          for attempt in {1..20}; do sleep 2; if curl -s http://localhost:6193/ > /dev/null; then break; fi; done
          TERM="${TERM:-dumb}"
          curl --location 'http://localhost:6191/test-endpoint' \
          --header 'Content-Type: application/json' \
          --data '{
              "data": "Test Message"
          }'
          cd test/cypress
          npm install
          sudo npm i -g cypress
          cypress install
          npx cypress run
