name: End-to-end tests for Frontend->FP->RP->Backend
on: [pull_request]
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upgrade node
        uses: actions/setup-node@v4
        with:
          node-version: "23.x"
      - name: Run services and do e2e tests
        run: |
          npm i -g concurrently && make run &
          sleep 150
          cd test/cypress
          npm install
          sudo npm i -g cypress
          cypress install
          cypress run